import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

cleanupOutdatedCaches();

// Default navigation route (SPA)
registerRoute(new NavigationRoute(new NetworkFirst({ cacheName: 'navigations' })));

// Cache JS/CSS
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({ cacheName: 'assets-cache' })
);

// --------------------------------------------------------------------------------
// PUSH NOTIFICATIONS HANDLING
// --------------------------------------------------------------------------------

self.addEventListener('push', (event) => {
    console.log('[SW] Push recibido:', event);

    let data = {
        title: 'KPoint',
        message: '¡Tienes una nueva actualización!',
        url: '/'
    };

    if (event.data) {
        try {
            data = event.data.json();
            console.log('[SW] Datos del push (JSON):', data);
        } catch (e) {
            data.message = event.data.text();
            console.log('[SW] Datos del push (Text):', data.message);
        }
    }

    const options = {
        body: data.message,
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        vibrate: [100, 50, 100],
        data: {
            url: data.url || '/'
        },
        actions: [
            { action: 'open', title: 'Ver detalle' }
        ],
        tag: 'kpoint-notification', // Evita duplicados
        renotify: true
    };

    event.waitUntil(
        self.registration.showNotification(data.title, options)
    );
});

// Click en la notificación
self.addEventListener('notificationclick', (event) => {
    console.log('[SW] Notificación clickeada:', event.notification.tag);
    
    event.notification.close();
    
    const urlToOpen = event.notification.data.url || '/';

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Si ya hay una ventana abierta con la app, enfocarla
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url.includes(urlToOpen) && 'focus' in client) {
                    return client.focus();
                }
            }
            // Si no hay ventana, abrir una nueva
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});
